import Head from 'next/head';
import { useEffect, useState } from 'react';
import { getCats } from '../services/cats';

export default function Home() {
  const [cats, setCats] = useState([]);

  useEffect(() => {
    if (cats.length === 0) {
      getCats().then((res) => setCats(res));
    }
  }, [cats]);

  console.log(cats);

  return (
    <div>
      <Head>
        <title>Picnic Cats</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <header>
        <h1>Picnic Cats</h1>
      </header>

      <main>Picnic</main>
    </div>
  );
}
